name: WHATSDOWN CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Whatsdown app
              uses: appleboy/ssh-action@v0.1.2
              with:
                  host: ${{secrets.SSH_IP}} # IP address of the server you wish to ssh into
                  username: ${{ secrets.SSH_USERNAME}} # User of the server you want to ssh into
                  password: ${{secrets.SSH_PASSWORD}}
                  script: |
                      pm2 stop all
                      rm -r -f server
                      git clone git@github.com:chombazm/friendly-funicular.git server # clone the repo into the 'server folder' folder
                      cd server
                      yarn install # install dependencies
                      yarn upgrade 
                      pm2 start server.js # start as a background service.
